### ISSUE TITLE
[object_detection] Layer PointCloud2 into ground_points and obstacle_points

### ISSUE THREAD

**Issue by bsubei** [chicagoedt/revo_robot#12]
Go to `isValidPoint` in the [source](https://github.com/ros-perception/image_pipeline/blob/indigo/stereo_image_proc/src/nodelets/point_cloud2.cpp#L155) and just add a bool function to the expression that returns false if a point is below a certain z threshold.

**Comment by bsubei** [comment]
this is for the part of stereo that will only look for barrels (and discard any points on the ground below a certain z threshold)

**Comment by bsubei** [comment]
@staylo32 is working on this

**Comment by l0g1x** [comment]
done in commit e3379ef4b619b9e8b2be69bd8139f795184b08e0
