### ISSUE TITLE
create a list of line_detection algorithms and make quick prototypes to test

### ISSUE THREAD

**Issue by bsubei** [chicagoedt/revo_robot#15]
this list should be maintained in the [Line Detection Algorithms wiki page](https://github.com/chicagoedt/Software_IGVC/wiki/Line-Detection-Algorithms).

**Comment by bsubei** [comment]
so far I found the Gabor filter. It's pretty cool as a edge detection filter...

**Comment by l0g1x** [comment]
@basheersubei can you paste the sha1 to where your commit is for the monochrome image filtering?

**Comment by bsubei** [comment]
HEAD of development branch should have this...  Or just use this ab1bdfcf532177d9ae7479719c966f05da1315c1. check the file [gabor-linedetection.py](https://github.com/chicagoedt/Software_IGVC/blob/development/line_detection/src/gabor-linedetection.py).

It takes in raw (meaning, uncompressed) ROS image messages and outputs compressed ROS images of the filters output. I'm using cv_bridge currently btw
