### ISSUE TITLE
find out why line_detection lags so much

### ISSUE THREAD

**Issue by bsubei** [chicagoedt/revo_robot#27]
investigate whether the queue size on the publisher (rosbag in this case) is higher than the subscriber (line_detection, which has queue_size 1)

or maybe it could be that the images are too large (1080p is probably the problem).

perhaps the algorithm is too demanding?

**Comment by bsubei** [comment]
we're clocking at 3fps with 1080p... Maybe a resize at the beginning will improve things (perhaps not?)

**Comment by bsubei** [comment]
tried queue_size 1 on rosbag publisher, also checked usb_cam (it has no buffer). This is probably not the reason... pursuing with resize

**Comment by bsubei** [comment]
apparently resizing does not fix the lag issue...

Maybe opencv library or the way I'm using it (look at imdecode) slowing things down?

**Comment by bsubei** [comment]
resizing does not fix the issue because the images I tried with are still 1080p to begin with (resizing them probably takes more time than gained by smaller operations).

Perhaps using lower resolution bags will work better. I will try to run the bags, then save them in smaller resolution.

**Comment by bsubei** [comment]
I wrote a resizer node (does nothing but resize the 1080p to desired resolution), and it was pretty snappy (few seconds lag but still reasonable). This rules out the encoding/decoding being the bottleneck.

I think the culprit could be the line detection algorithm itself. I just resaved all the compressed bags as 240p using the resizer node. I'll test the line_detection with it

**Comment by bsubei** [comment]
240p on line_detection still lags. It improved framerate a lot now, but there's huge laaaag. Something is wrong with the line_detection algorithm... It's just way too laggy (but it's strange because queue size is 1, yet it lags 20 seconds behind and if you cut the rosbag, line_detection still keeps going)

**Comment by wfriedl** [comment]
What is the average time per step in the pipeline?

**Comment by oxoocoffee** [comment]
Basheer,

Give me call to talk about it end of day. I am in meetings all day so will not be able to talk most of the day.
Call me after 6 PM or look me up on Skype evening

-- 
Robert J. Gebis
Sent with Airmail

On October 29, 2014 at 6:50:33, Warren Friedl (notifications@github.com) wrote:

What is the average time per step in the pipeline?

**Comment by bsubei** [comment]
it's basically getting input at a faster rate than it can output (and therefore the input frames queue up). I don't know why it queues them although queuesize is 1... maybe I should double check it?

**Comment by oxoocoffee** [comment]
So you definitely do have publisher queue set to 1?  
The only case I can think of now top of my head is:

           -------------       --------------------       ------------
Camera ==> | Your Code |  ===> | Pub Queue Size 1 | ====> | Consumer |
           -------------       --------------------       ——————------
1. Based on how queue is implemented "Your Code” could block when trying insert message to “Pub Queue Size” is size 1 Instead of “replacing it”.
2. If above is true then it means that Consumer is no picking it up fast enough.

Now to test if queue blocks if there is no space, Increase Pub Queue Size and run. Check if this queue gets filled. If it is filled then look at Consumer processing rate. If its processing rate is slower then Pub queue size then you know the problem is on Receiving/processing side.

If consumer can’t be optimized then I would look into API if there maybe is a call to post to queue with replacing various appending with possible blocking. Maybe there is a way to add hook/callback to queue that is called when size is above certain point. If such callback can be added to queue then set size to queue == 2. In callback just remove and “delete” if you not already using shared pointers. So callback would guarantee that there is always one empty place in queue so publisher would not block.

I need little more observations to give better fix/solution.

Robert J. Gebis
Sent with Airmail

**Comment by wfriedl** [comment]
So how long does it take to process a frame?

**Comment by bsubei** [comment]
@oxoocoffee my node (backproject_noskel) takes input from the rosbag images, and outputs filtered images. I set both the rosbag output and my node subscriber to queue size 1 but it still looks like it's somehow buffering images (when I stop the rosbag and kill it, my node still processes like 40 frames or so).

right now, it's doing around 4~5Hz with 240p image. I'll play around with my algorithm and see which operation is costing us the most (i'm pretty sure it's just one of them that's costly).

**Comment by l0g1x** [comment]
any progress?

**Comment by bsubei** [comment]
I started getting this to work perfectly (but frequently would get those weird rostime errors)... Sometimes it lags and stuff... I'm suspecting it might have to do with playing rosbags... Or maybe I switched from using cv_bridge (now I do direct conversion)?

**Comment by l0g1x** [comment]
which commit fixes this issue so i can take a look at how you process time stamps

**Comment by bsubei** [comment]
Just realized the most current version ab1bdfcf532177d9ae7479719c966f05da1315c1 uses cv_bridge (which afaik works fine most of the time). Maybe when I was directly converting them, it somehow was lagging or didnt process the time stamps correctly.

**Comment by bsubei** [comment]
easy hack to fix this: just publish data to the line_detection node slower and it won't choke and queue up the images and cause lag

**Comment by bsubei** [comment]
ok, fixed this! This guy posted [a question](http://answers.ros.org/question/50112/unexpected-delay-in-rospy-subscriber/) with exactly my problem. It turns out the problem (I think) is that the buff_size (which defines how many bytes the queue buffer can hold) is set as default (according to [this](http://docs.ros.org/indigo/api/rospy/html/rospy.topics.Subscriber-class.html)) to 65536, which is too small for our image messages. This causes something weird to happen in rospy, and it looks like it sets the queue_size to infinite default (even though I told it size is 1).

Anyways, now the queue_size is actually equal to 1, and the output rate is 8Hz (needs to be improved).

**Comment by bsubei** [comment]
[here's the source code](https://github.com/ros/ros_comm/blob/6868cbf4804339d504ba59940dcccb63bfd3743c/clients/rospy/src/rospy/topics.py) where buff_size is used. I'm going to dig in and see what's going on. Maybe there's a bug.

Also, I need to figure out what buff_size to set (right now i'm using an arbitrary 2**24, which is way too big)

**Comment by bsubei** [comment]
couldn't figure out why this was happening. Maybe it's just obvious that buff_size has to be large enough for your messages (and that isn't handled by rospy automatically).

Either way I posted an [issue here](https://github.com/ros/ros_comm/issues/536)

**Comment by bsubei** [comment]
sort of fixed in 09744f9c4596bc0a3842abc12b76a4ae2d4b8669 , still need to find appropriate buff_size based on our images and resolutions.

**Comment by bsubei** [comment]
tried running `rostopic bw` on some of the rosbags with images. The max I've seen is 0.4MB per message, so I'll just set the buff_size to be 0.5 MB, which is close to 2^19.

**Comment by bsubei** [comment]
maybe I can try out setting the buff_size as a param to be run in launch file?

**Comment by bsubei** [comment]
fixed in 34fc91a8662ef2f833af6865df0894d2b122917b. Further tweaking might be needed. But it works for now
