### ISSUE TITLE
find out if Travis CI can be used with ROS

### ISSUE THREAD

**Issue by bsubei** [chicagoedt/revo_robot#34]
so far the only Travis-y thing I found in a ROS repo is this
https://github.com/ros-planning/warehouse_ros/blob/master/.travis.yml

**Comment by bsubei** [comment]
this ROS package here managed to do it, and they have a whole lot of travis yml config files
https://github.com/lagadic/vision_visp

**Comment by bsubei** [comment]
works! it compiles successfully now.

Now we need to figure out how to make it run tests (in both C++ and Python at the same time)

https://travis-ci.org/basheersubei/Software_IGVC/builds/40448433

**Comment by bsubei** [comment]
also, we need to clean up the travis config file a bit (it downloads and installs some packages we dont need)

**Comment by bsubei** [comment]
- [ ] clean up travis config
- [ ] figure out ARM cross-compiling for travis
- [ ] have it run both C++ and Python tests

**Comment by bsubei** [comment]
still need to figure out ros dependencies and packages for indigo

**Comment by bsubei** [comment]
turns out Travis doesn't support Ubuntu 14.04, which means ROS Indigo cannot be used with it... The dependencies just won't install on Ubuntu 12...

Will abandon Travis for our repository for now. @l0g1x is working on setting up a Jenkins server instead

**Comment by bsubei** [comment]
Keep an eye on travis issue for updating to Ubuntu 14.04``
https://github.com/travis-ci/travis-ci/issues/2046

**Comment by l0g1x** [comment]
Jenkins is working now so closing this
