### ISSUE TITLE
import nmea_navsat_driver as a submodule from the original repo

### ISSUE THREAD

**Issue by bsubei** [chicagoedt/revo_robot#35]
so far, the changes we made were applied onto the 0.3.3 release (on my fork) to a new branch called edt-devel, and now we can use that newest commit as the version our submodule will be.

**Comment by bsubei** [comment]
I just realized the changes are so minor that we can just apply them onto the newest branch `indigo-devel` instead of on 0.3.3 release, which means we can merge our additions to the driver to upstream...

**Comment by bsubei** [comment]
i reapplied the changes on the `indigo-devel` branch (HEAD). It should all be the same. Not tested (no access to hardware yet)

https://github.com/basheersubei/nmea_navsat_driver

**Comment by bsubei** [comment]
fixed in pull request #32

**Comment by l0g1x** [comment]
fixed in 405b8792576341ffca7699763a00d4d1f60916ab
