### ISSUE TITLE
nmea_navsat_driver changes that add IMU heading publisher needs code review

### ISSUE THREAD

**Issue by bsubei** [chicagoedt/revo_robot#36]
https://github.com/basheersubei/nmea_navsat_driver/commit/390e03c2848535446c9cded2323eea847aa35c88

no clue what some of these changes are... HDT?

**Comment by bsubei** [comment]
http://www.trimble.com/OEM_ReceiverHelp/V4.44/en/NMEA-0183messages_HDT.html

http://aprs.gids.nl/nmea/#hdt

found HDT mentioned here

**Comment by bsubei** [comment]
now I understand.

The additions make the GPS driver parse in HDT sentences (which contains heading information), and then it publishes an Imu message containing that heading only (rest are zeros)

**Comment by bsubei** [comment]
https://github.com/ros-drivers/nmea_navsat_driver/issues/11

just saw this. Let's review the current solution we made (especially using an Imu mesage instead of something like a QuaternionStamped)

**Comment by bsubei** [comment]
this commit contains the changes
https://github.com/basheersubei/nmea_navsat_driver/commit/d4a183b2624b090a1f56683d412484e9a6f368fc

**Comment by l0g1x** [comment]
sorry just saw this.. yes the HDT string i believe just comes in the simple format '$HDT (0-360)' the integer signifying the degrees from facing north. However, 0 degrees (default: north) may vary, depending on what orientation you program the gps to (basically faking which direction is north). I believe the offset right now is -90 degrees, but might be +90, have to double check but for now it is setup properly

**Comment by bsubei** [comment]
ok the nmea_navsat_driver is included in the repo as a submodule. We'll make changes whenever we work on the gps_goal or whatever.
