### ISSUE TITLE
incorporate roslint into our packages

### ISSUE THREAD

**Issue by bsubei** [chicagoedt/revo_robot#37]
http://wiki.ros.org/roslint

this means that every time packages are compiled, they are checked for neatness and coding style...

**Comment by l0g1x** [comment]
is this necessary? we will get varied results since some people use sublime and some people like myself use vim which has different indentation's. I don't know if this is the case, can someone verify?

**Comment by bsubei** [comment]
no the indentations should not be different (you just set it to the standard 4-spaces). It helps us keep the coding style standardized (variable names, comments, curly braces, etc). Makes it look much cleaner. Doesn't take that much time really.

**Comment by oxoocoffee** [comment]
There is a way to specify tab spaces and such in ~/.vimrc. Google it
