### ISSUE TITLE
set up jenkins CI server for ROS indigo

### ISSUE THREAD

**Issue by bsubei** [chicagoedt/revo_robot#42]
previous attempt at CI using Travis #34 failed due to unsupported Ubuntu 14 (so no indigo).

Will attempt to use Jenkins server to build new pushed code and run tests. This should be feasible as @wfriedl previously tested it.

**Comment by l0g1x** [comment]
Wont install dependencies on server side ubuntu 14.04 because ttf-dejavu-core_2.34-1ubuntu1_all.deb is crashing on ros indigo full desktop install. Going to see what i can figure out because im not sure if the VPS from digital ocean can install gazebo or not. will look later

**Comment by bsubei** [comment]
is that package even necessary? It's just a dummy package for a font package... There's gotta be a way to get rid of it

**Comment by bsubei** [comment]
don't do a full desktop install on the digitalocean VPSs. Their Ubuntu images don't have GUI. Just install the core ros stuff and then install the ros packages we need.

**Comment by l0g1x** [comment]
Well i cant.. Do it another way because i have gazebo based dependencies listed in the package.xml for simulation packages...

**Comment by bsubei** [comment]
well then just don't build the simulation packages... either don't include them when building (you can always tell ur Jenkins server to remove that folder before catkin_make) or take them out of the repo. I prefer the first option (it's less work).

**Comment by bsubei** [comment]
regardless of what server we use to run Jenkins, you should not be building or installing any GUI elements for ROS in a CI environment. There is no need.

**Comment by l0g1x** [comment]
All finished for IGVC, RMC, and Firmware

**Comment by bsubei** [comment]
wait, did you limit registration to the Jenkins server?

**Comment by l0g1x** [comment]
I am leaving the sign up on there, since on the backend i have matrix-based security enabled anyway which won’t allow anyone who isn’t in the matrix to create a account. This saves some time when we want to create a member on the team a account to set up their own job.
