### ISSUE TITLE
[visual odometry] look at viso2_ros package for visual odometry using stereo

### ISSUE THREAD

**Issue by bsubei** [chicagoedt/revo_robot#5]
looks like [viso2_ros](http://wiki.ros.org/viso2_ros) can do visual odometry (SLAM) using stereo images without any extra parameters.

**Comment by l0g1x** [comment]
Will are most likely going to use this package, and the pointcloud2 will be fed in from the duo3d output.

**Comment by l0g1x** [comment]
Going to use rtabmap instead
