### ISSUE TITLE
[line_detection] compare RANSAC line fitting with Hough transform

### ISSUE THREAD

**Issue by bsubei** [chicagoedt/revo_robot#53]
Try implementing RANSAC using the opencv fitline method according to this [SO answer](http://stackoverflow.com/a/15184899/341505).

**Comment by bsubei** [comment]
"If you convert your output as it is right now to a pointcloud, the PCL library has a RANSAC method already implemented so you wouldnt need to do anything by hand" - Krystian

**Comment by l0g1x** [comment]
- [ ] Try implementing RANSAC using the opencv fitline method according to this [SO answer.](http://stackoverflow.com/a/15184899/341505)
- [ ] try converting current output of line detection into pointcloud2
- [ ] apply RANSAC to that pointcloud2

**Comment by bsubei** [comment]
I wonder whether not knowing how many lines we have (either one or two) will be a problem for RANSAC. Maybe we have to use line clustering instead like in #54 to figure out how many.

**Comment by l0g1x** [comment]
@basheersubei have you tried implementing a RANSAC model yet?

**Comment by bsubei** [comment]
yes, it didn't work well. The problem is mainly with the filtering stage that happens before this. Too much noise

https://github.com/basheersubei/Software_IGVC/commit/313e58e58c776417de79f7bb73ca785b5512383e

**Comment by bsubei** [comment]
no need for line fitting, we will just throw the output of image pixels into a pointcloud
