### ISSUE TITLE
Add backprojection training image to installEDT bash script

### ISSUE THREAD

**Issue by bsubei** [chicagoedt/revo_robot#59]
I need the install script to add a folder called `training_images` inside `misc` folder inside of line_detection package. It should then place an image with the name `training_for_backprojection_1.png`. This image can be found [here](https://drive.google.com/file/d/0B1Ba5iax8CW8aEYtVWh0Q1Z6NU0/view?usp=sharing)

**Comment by l0g1x** [comment]
Upload the image to the edt wiki server and give me the url to where the actual location of the file is on the server and tell me where you want the image to be placed

**Comment by bsubei** [comment]
the image url is in the github wiki, but lemme paste it here anyways
https://drive.google.com/file/d/0B1Ba5iax8CW8aEYtVWh0Q1Z6NU0/view?usp=sharing

**Comment by bsubei** [comment]
you know what, forget this task. I'm replacing the training thing with txt files anyways
