### ISSUE TITLE
[robot_localization] use Twist as wheel odometry input for robot_localization

### ISSUE THREAD

**Issue by bsubei** [chicagoedt/revo_robot#6]
instead of using our own odometry node and publishing Twists for wheel velocity into robot_localization, we'll just straight up take those Twists from roboteq_node.

Check that robot_localization can handle Twists.

**Comment by l0g1x** [comment]
odomN_config, ****_twistN_config**_***, imuN_config, poseN_config - For each of the sensor messages defined above, users must specify what variables of those messages should be included. An example odometry configuration might look like this:
    <rosparam param="odom0_config">[true, true, false, false, false, true, true, false, false, false, false, true]</rosparam>
The order of the boolean values are x, y, z, roll, pitch, yaw, x velocity, y velocity, z velocity, roll velocity, pitch velocity, and yaw velocity. Please see the Sensor Integration tutorial for more information.

**Comment by bsubei** [comment]
above text from [robot_localization ros wiki](http://wiki.ros.org/robot_localization)
