### ISSUE TITLE
[roboteq_node] move wheels_msg to roboteq_node since it's only used there

### ISSUE THREAD

**Issue by bsubei** [chicagoedt/revo_robot#7]
wheels_msg is currently inside base_controller (which doesn't use wheels_msg). Instead, let's define wheels_msg inside roboteq_node (where it is used).

Make sure the CMakeLists for both packages fixes this. Don't want any missing message headers errors popping up

**Comment by l0g1x** [comment]
roboteq_node uses its own msg type for wheels_msg. Refer to roboteq_node/msg folder

**Comment by bsubei** [comment]
correct. I just realized that. Will remove wheels_msg from base_controller.

**Comment by l0g1x** [comment]
Submit a pull request. Don’t push straight to the master

Krystian Gebis
University of Illinois - Chicago
Chicago EDT - Robotics (Software)
Undergraduate Computer Engineering

**Comment by bsubei** [comment]
I pushed it to development branch. It builds on my system. Try it on yours.

**Comment by bsubei** [comment]
can someone test this to confirm?
