### ISSUE TITLE
Implement robot_upstart into Radxa's

### ISSUE THREAD

**Issue by l0g1x** [chicagoedt/revo_robot#70]
Robot_upstart is a package which allows you to create Ubuntu Start-up processes. We need to set this up to start all the driver node's, just not the nav stack.

http://wiki.ros.org/robot_upstart

**Comment by bsubei** [comment]
sounds easy as hell (and worth it). Just run something like

`$ rosrun robot_upstart install myrobot_bringup/launch/base.launch`

**Comment by l0g1x** [comment]
In order to prevent having to keep a sensor permanently assigned to one of the boards, we need to write a script that checks whether /dev/ttyACM0 (we need to udev this so its /dev/roboteq) is available on that board. That way, it doesnt matter what board the sensor is plugged into, the script will determine what background processes to actually execute

Krystian Gebis
University of Illinois at Chicago

**Comment by bsubei** [comment]
yeah, so we can write scripts for these. Hint: they have a Python API for robot_upstart

;)
