### ISSUE TITLE
fresh install on scipiotop

### ISSUE THREAD

**Issue by bsubei** [chicagoedt/revo_robot#78]
we need to be running Indigo and Ubuntu 14...
- back up any data we need (rosbags or code that's not checked in)
- install ubuntu
- install indigo and all dependencies (try the install bash script)

**Comment by sabinoj** [comment]
Keep in mind that we have two 64GB hard drives in Scipio, so if you would
like to just back up all of the bags off of the other one and set a fresh
install of Ubuntu 14.04 on it I think that would be the best idea.

```
      --John Sabino
```

**Comment by bsubei** [comment]
Bags shouldn't be that big and I have a couple of 16 GB flash drives. Also I have a TB of Dropbox space so I can just plop them there. I just have to get the time to do it
