### ISSUE TITLE
[hector_mapping] look at hector_mapping as a SLAM algorithm

### ISSUE THREAD

**Issue by bsubei** [chicagoedt/revo_robot#8]
we're currently trying out [hector_mapping](http://wiki.ros.org/hector_slam) using only the laser.

we have to figure out whether hector_mapping would work for IGVC. We're pretty sure we can't use hector_mapping alone to localize (because there aren't enough barrels around and lines don't always show up), so we might use hector_mapping's localization data and throw that into the EKF (robot_localization) with the rest of the localization data (wheel odometry, GPS, and IMU)

**Comment by l0g1x** [comment]
Should we still try to implement this? Maybe this might work once we mount the 2nd sicktim on the back
