### ISSUE TITLE
Broken link for rosbag repository

### ISSUE THREAD

**Issue by bergercookie** [chicagoedt/revo_robot#89]
In the [rosbag-repo page](https://github.com/chicagoedt/revo_robot/wiki/Rosbag-Repo) the Dropbox URL provided seems to be broken.

Can you fix this? Is there an alternative download link?

**Comment by bsubei** [comment]
sorry about that, I fixed the URL

**Comment by l0g1x** [comment]
@bergercookie would you be able to share the results you get from this dataset in your project? The datasets are recorded camera data for a robotics competition IGVC and our organization would love to learn from whatever you end up doing with the data (if confidentially possible)

**Comment by bergercookie** [comment]
@l0g1x Currently I develop a SLAM algorithm that makes use of laser scans and odometry data but support for camera data, 3D Point clouds is on its way. In case I use the datasets I will not hesitate to provide feedback.

**Comment by l0g1x** [comment]
@bergercookie awesome thanks! good luck on your project. Feel free to ask us for any help, someone will try to respond when they can
