### ISSUE TITLE
[roboteq_node] finalize roboteq_node and test that the serial port bug has been fixed

### ISSUE THREAD

**Issue by bsubei** [chicagoedt/revo_robot#9]
prior to the 2014 IGVC, the roboteq_node had serial port errors. Robert reports that he fixed them, but he never pushed the fixes to the main repo. Let's get those fixes and also test that the serial port no longer exists

**Comment by oxoocoffee** [comment]
Potential Fix 311d04e660847ab1e2ae9ca790eeb7fcbec873ef

**Comment by bsubei** [comment]
need to test this on Roboteqs to confirm no more bugs

**Comment by l0g1x** [comment]
The node has been recently acting wierd on the Jetson TK1. @oxoocoffee started looking into it last friday

**Comment by oxoocoffee** [comment]
As far as I can tell nothing wrong with roboteq. Looks like sometimes we are NOT Sending data to it therefore no data to read FROM roboteq. 
I will look at this again when back to Chicago
